baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Mindful Hugo Personal Website Theme'

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = true
    style = 'vs'
    tabWidth = 4
